title: Course-project
email: viki.radeva91@gmail.com
description: Course-project
destination: docs
baseurl: "/" 
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  viki.radeva91

# Build settings
plugins:
  - jekyll-feed

#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
